name: build-docker

on: push

env:
  IMAGE: oauth2-proxy
  VERSION: v7.0.0
  EXTRA_TAG: "-prerelease"

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: oauth2-proxy/oauth2-proxy
          path: source
          ref: a0d37518e0192e00bb20213c3d507760dcefcfb2

      - name: Set Dynamic Env Vars
        run: |
          IMAGE_TAG=gresearchdev/${IMAGE}:${VERSION}${EXTRA_TAG} && \
          IMAGE_FILE_NAME=$(basename ${IMAGE_TAG} | sed 's/:/_/').docker.tar.gz && \
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV && \
          echo "IMAGE_FILE_NAME=${IMAGE_FILE_NAME}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg VERSION=${VERSION} \
            --tag ${IMAGE_TAG} source/.

      - name: Save Image to Disk
        run: docker save ${IMAGE_TAG} | gzip > ${IMAGE_FILE_NAME}
